version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting install phase..."
      - pwd
      - ls -la

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - npm install
      - npm run lint

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building Lambda functions..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  name: BuildArtifact